apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration 
  template:
    metadata:
      labels:
        app: expiration 
    spec:
      containers:
        - name: expiration 
          image: 190097/expiration
          env:
            - name: NATS_URL
              value: 'http://nats-service:4222'
            - name: NATS_CLUSTER_ID
              value: ecommerce
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: expiration-redis-service
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
